### ISSUE TITLE
Error whe editing note created by QOwnNotes

### ISSUE THREAD

**Issue by ayevee** [aykit/MyOwnNotes#126]
When I create a note in and then edit it in MyOwnNotes I get sync error.

The following excpetion is logged server-side:

```
Exception: {"Exception":"OCP\\Files\\InvalidPathException","Message":"File name contains at least one invalid character","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/lib\/private\/files\/view.php(663): OC\\Files\\View->verifyPath('\/ivan\/files\/Not...', 'Note 2015-12-24...')\n#1 \/volume1\/web\/owncloud\/lib\/private\/files\/node\/file.php(146): OC\\Files\\View->rename('\/ivan\/files\/Not...', '\/ivan\/files\/Not...')\n#2 \/volume1\/web\/owncloud\/apps\/notes\/service\/notesservice.php(126): OC\\Files\\Node\\File->move('\/ivan\/files\/Not...')\n#3 \/volume1\/web\/owncloud\/apps\/notes\/controller\/notesapicontroller.php(132): OCA\\Notes\\Service\\NotesService->update(42184, 'Note 2015-12-24...', 'ivan')\n#4 \/volume1\/web\/owncloud\/apps\/notes\/controller\/errors.php(31): OCA\\Notes\\Controller\\NotesApiController->OCA\\Notes\\Controller\\{closure}()\n#5 \/volume1\/web\/owncloud\/apps\/notes\/controller\/notesapicontroller.php(133): OCA\\Notes\\Controller\\NotesApiController->respond(Object(Closure))\n#6 [internal function]: OCA\\Notes\\Controller\\NotesApiController->update(42184, 'Note 2015-12-24...')\n#7 \/volume1\/web\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#8 \/volume1\/web\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Notes\\Controller\\NotesApiController), 'update')\n#9 \/volume1\/web\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Notes\\Controller\\NotesApiController), 'update')\n#10 \/volume1\/web\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('NotesApiControl...', 'update', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/volume1\/web\/owncloud\/lib\/private\/route\/router.php(282): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/volume1\/web\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/notes\/api...')\n#14 \/volume1\/web\/owncloud\/index.php(39): OC::handleRequest()\n#15 {main}","File":"\/volume1\/web\/owncloud\/lib\/private\/files\/view.php","Line":1719}
```

**Comment by maltefiala** [comment]
Hej @ayevee , what is QOwnNotes?

**Comment by ayevee** [comment]
@maltefiala , that's a desktop client for OwnNotes (http://www.qownnotes.org/)

**Comment by rudo54** [comment]
I have the same issue here

**Comment by pbek** [comment]
What is the content of that note?

**Comment by rudo54** [comment]
These are text-only notes, formatted by markdown.
Just like this:

Note 2016-02-07T21.32.18
========================

Test

**Comment by pbek** [comment]
Would such a name work, @maltefiala ?

**Comment by pixelrust** [comment]
Yesterday I lost a few updates I had made to a note. 

I had edited it from Android (MyOwnNotes), from web (Owncloud web interface) and from desktop (Linux official client), possibly almost at the same time. Unfortunately, I didn't track all updates and actions.

Given @pbek 's question I'll note that at some point I had mistakenly renamed the note this way:
### System

**Comment by maltefiala** [comment]
MyOwnNotes 2 is live. Complete rewrite, issue closed
